---
all:
  vars:
    ansible_user: ansible
    ansible_become: true

  children:
    load_balancers:
      hosts:
        k8s-lb-01:
          ansible_host: 10.10.1.10
          keepalived_priority: 150
          keepalived_state: MASTER
        k8s-lb-02:
          ansible_host: 10.10.1.11
          keepalived_priority: 100
          keepalived_state: BACKUP

    control_plane:
      hosts:
        # Первый узел группы инициализирует кластер (kubeadm init),
        # остальные присоединяются. Порядок значим.
        k8s-cp-01:
          ansible_host: 10.10.1.21
        k8s-cp-02:
          ansible_host: 10.10.1.22
        k8s-cp-03:
          ansible_host: 10.10.1.23

    workers:
      hosts:
        k8s-worker-01:
          ansible_host: 10.10.1.31
        k8s-worker-02:
          ansible_host: 10.10.1.32
        k8s-worker-03:
          ansible_host: 10.10.1.33

    kubernetes:
      children:
        control_plane:
        workers:
